### PR TITLE
fix(deps): Fix `poetry install`

### PR DESCRIPTION
**Pull request by malmeloo**
Fixes `poetry install` by constraining the `pyinstaller` build dep to python `<3.13`.

Poetry suggests to fix this by changing the supported Python version to `>=3.10,<3.13`, but I don't think it's desirable to limit future version support to how quickly Pyinstaller updates.

### CODE REVIEW

**Comment by Elsie19** [comment]
Is this in relation to the recent PR @srd424 made?

**Comment by malmeloo** [comment]
I don't think so? But the issue it fixes can be observed in #267 and #268. This simply doesn't install pyinstaller for >=3.13 because it doesn't indicate support for those versions.

**Comment by Elsie19** [comment]
@D-Brox I need your opinion as you're the only python guy at the moment.

**Comment by srd424** [comment]
Someone who actually understands the python ecosystem should probably look at _why_ #271 works some time :) In particular I suspect a proper review of the anyio / httpcore / httpx versions etc. would fix things "properly."

**Comment by Elsie19** [comment]
True, our main guy @wizard-28 who's in charge of pacup has been gone for a hot minute so pacup has had basically no development since he went.

**Comment by malmeloo** [comment]
I will take a look at it today or tomorrow.

**Comment by malmeloo** [comment]
...or now :-)

That error is a bug in httpx which is fixed in the latest version: https://github.com/encode/httpcore/issues/825

If you merge this PR and then rebase + merge #216, it will be fixed. I just tested it and can confirm it now works on 3.10.

**Review by D-Brox — APPROVED** [review]

**Comment by Elsie19** [comment]
@D-Brox you can handle this PR, idk much about python dependencies and stuff like that.

**Comment by Elsie19** [comment]
Hey so quick update @malmeloo, we've decided, to rewrite pacup in Perl. So we won't have to deal with python issues anymore 😁, along with it being much easier to interface with bash.

**Comment by malmeloo** [comment]
Yes I've been lurking in the discord and following along somewhat, nice! I'm sure that's gonna be way nicer than the cursed pacscript parser pacup has now.

**Pull request closed without merging**
